name: Manually Triggered Torque Blueprint Launch

on:
  workflow_dispatch:

jobs:
  start-torque-environment:
    runs-on: ubuntu-latest
    steps:
    - name: Start Torque Environment
      id: start-env
      uses: QualiTorque/torque-start-environment@v1
      with:
        space: NN-SE-Candidate-Exercise
        blueprint_name: ssm
        repository_name: BH_Torque_examples
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        duration: 120
        timeout: 30
