name: Torque Environment Pipeline

on:
  workflow_dispatch:

jobs:
  Launch-stop-torque:
    runs-on: ubuntu-latest
    steps:
    - name: Start Torque Environment
      id: start-environment
      uses: QualiTorque/torque-start-environment@v1
      with:
        space: NN-SE-Candidate-Exercise
        blueprint_name: ssm
        repository_name: BH_Torque_examples
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        duration: 30
        timeout: 30
        inputs: 'name=${{ github.run_number }},value=value_${{ github.run_number }}'

    - name: Delay for 6 minutes
      run: sleep 360

    - name: End Torque Environment
      uses: QualiTorque/torque-end-environment@v1
      with:
        space: NN-SE-Candidate-Exercise
        environment_id: ${{ steps.start-environment.outputs.environment_id }}
        torque_token: ${{ secrets.TORQUE_TOKEN }}
